# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UrahtguSnUBnyRy4wMkFvyPEgqVuDCy0
"""
import os
import cv2 

# this function is for read image,the input is directory name
def read_directory(directory_name):
    # this loop is for read each image in this foder,directory_name is the foder name with images.
    for filename in os.listdir(r""+directory_name):
        print(filename) #just for test
 
        img = cv2.imread(directory_name + "/" + filename)
        sp = img.shape
        sz1 = 4*sp[0]#height(rows) of image
        sz2 = 4*sp[1]#width(colums) of image
        res=cv2.resize(img,(sz2,sz1),interpolation=cv2.INTER_CUBIC)
        #os.chdir("images")
        cv2.imwrite(directory_name + "/" + filename,res)

#read_directory("images/")
